### ISSUE TITLE
Special Skins limit to 126 after that game crashing 

### ISSUE THREAD

**Issue by Samthapa76** [thelink2012/modloader#100]
Hey there [thelink2012]

i have been looking for solution for it but cant done without asking you can you please increase limit of special skins (added skins i mean ) when i browse skin which is in modloader after 126 skins it crash game gta sa i try [overdirve ](https://www.gtainside.com/en/sanandreas/tools/46380-gta-override-1-3/) it can hold like 1000 skins and no crash sadly i am using it now but moadloader is way handy to use but modloader has limit to 126 skins only please can you fix that ? thanks for reading

**Comment by thelink2012** [comment]
Try Skin Selector adapted for Mod Loader: https://www.mixmods.com.br/2015/09/skin-selector-v2-1-ml-e-v2-1-c/

**Comment by Samthapa76** [comment]
hey there i am so happy that you reply wow 

? because all modders are proudy or no time or they don't care they never reply but you did thanks and yea problem is non skin selector will work you try once its a limit of modloader normal skins i mean peds all they works great in modloader but added skins has limit and about that i found solution now i can use 100 to 1000000 skins no problem now thanks for reply again you cool thanks

**Comment by thelink2012** [comment]
No problem. Have a nice day :-)
