### ISSUE TITLE
Feature request: Support for ReVC and Re3

### ISSUE THREAD

**Issue by yuksel-kadir** [thelink2012/modloader#104]
Is it possible to add support for ReVC and Re3?

**Comment by thelink2012** [comment]
Yes. There is a branch with initial support as well as an re3 fork of mine
that integrates with that branch. Unfortunately I have since stopped work
on it because of T2's DMCA on the project.

**Comment by yuksel-kadir** [comment]
Okey, thank you for the answer :)
