### ISSUE TITLE
Add SCRIPT sound directory support

### ISSUE THREAD

**Issue by krook1024** [thelink2012/modloader#27]
Some sound mods needs to be loaded from the SCRIPT sound directory but the modloader script doesn't support them (due to modloader only can load the GENRL sound directory). Can you add that feature? Thanks alot and sorry for my bad english.

**Comment by thelink2012** [comment]
It's added as of f794453 currently in the dev branch, should be available in the next release :dancer:

**Comment by krook1024** [comment]
Thanks a lot, I'm gonna close the ticket.
