### ISSUE TITLE
Allow 32GB image files

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/modloader#32]
At `CdStreamThread` when reading off `cd->nSectorsToRead` and `cd->nSectorOffset` use a `uint64_t` instead of a `size_t`. Then setup also the `OVERLAPPED::OffsetHigh` field.

Even though Mod Loader's intentions are to avoid using img files, it doesn't hurt to do such a small change, specially when I'm the only one with access to the CdStreamThread! Thanks to fastman92 for the heads up.

**Comment by thelink2012** [comment]
32GB? Seems to be 8GB _(UINT32_MAX * 2048)_.

**Comment by quiret** [comment]
Splendid. Big IMG archives will become standard thanks to you! :)
