### ISSUE TITLE
Abstract over streaming structures

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/modloader#34]
We need to build an abstraction over the following structures:
* [x] CStreamingInfo
* [x] CdStream
* [x] CdStreamInfo
* [x] CDirectory

This is because they are, or may be, different on other game versions (i.e. between III, VC and SA), so a good abstraction over the structure ‒ that would at the end modify or fetch the real structure ‒ would be great.

This is important for the implementation of #25 and #33.

**Comment by thelink2012** [comment]
Okay, that'll do it.

**Comment by quiret** [comment]
Cool work :) I find your work on the streaming structures inspiring.

**Comment by thelink2012** [comment]
Thanks :D
