### ISSUE TITLE
Identify and warn about non UTF-8 readmes

### ISSUE THREAD

**Issue by thelink2012** [thelink2012/modloader#43]
On _std.data_ we currently don't support non-UTF-8 (actually non-ASCII) text files. We should identify those and ignore/translate and warn about it.

See report [here](http://gtaforums.com/topic/669520-mod-loader/?p=1067125810). Example [mod](http://gtadrom.com/load/mashiny_dlja_gta_san_andreas/lincoln/lincoln_continental_sedan_53a_1962/36-1-0-7046).

**Comment by thelink2012** [comment]
Translating doesn't seem to hard at the current codebase if we have a proper unicode library.

**Comment by thelink2012** [comment]
No warning needed! Supports UTF-8, UTF-16 and UTF-32 encoded readmes!

**Comment by quiret** [comment]
UTF-8 sucks. It is this fake ASCII encoding that you do not expect ^^

**Comment by thelink2012** [comment]
[I have to disagree](http://utf8everywhere.org/)! Though yeah, care must be taken, that's true for any encoding :)

**Comment by quiret** [comment]
So what makes a UTF-8 a UTF-8.... o_o
