### ISSUE TITLE
Link somehwere back to gtaforums?

### ISSUE THREAD

**Issue by mirh** [thelink2012/modloader#57]
Like in readme?
http://gtaforums.com/topic/669520-mod-loader/

**Comment by thelink2012** [comment]
I think there's a link to GTAF on the readme: https://github.com/thelink2012/modloader/blob/master/doc/readme/Readme.md (CTRL+F GTA Forums).

Something I'm missing here?

**Comment by mirh** [comment]
I'm dumb :s
