### ISSUE TITLE
FREEZING AFTER SAVING

### ISSUE THREAD

**Issue by De1mA** [thelink2012/modloader#62]
Whenever i save my SA, when I try to load a new savegame or go to a new mission, game just freezes off. and yeah that's the problem

**Comment by thelink2012** [comment]
Sure it's caused by mod loader not anything else?

**Comment by Tmp341** [comment]
Have you tried it without mod loader? If yes, open the game and try unchecking your mods one by one.

**Comment by De1mA** [comment]
Thanks, I resolved problem by just renaming one catalog/ ot was
insanity_audio. somehow renaming it worked. maybe just modloader bug

2016-09-20 22:00 GMT+03:00 Tmp341 <notifications@github.com>:
