### ISSUE TITLE
Widescreen Mod breaks Modloader from loading mods

### ISSUE THREAD

**Issue by empsmoke** [thelink2012/modloader#73]
Is this theLink2012?
ThirteenAG's Widescreen Mod breaks ModLoader from running.

**Comment by thelink2012** [comment]
@ThirteenAG what is this?

**Comment by ThirteenAG** [comment]
@thelink2012 No idea, everything works for me.

**Comment by empsmoke** [comment]
No, not in SA and GTA3, it's an error when I launch Vice City, that prevents Mod Loader from loading because of the Ultimate ASI Loader, so we need a ModLoader config file where it's you can set the directory of ModLoader if it's outside or inside the scripts folder.
![error](https://user-images.githubusercontent.com/14072545/37239916-8e625402-244b-11e8-9aaf-12e4a32471b9.PNG)

**Comment by thelink2012** [comment]
Move modloader.asi into the scripts directory. But leave the modloader directory in the root directory.
