### ISSUE TITLE
sound effects loader 

### ISSUE THREAD

**Issue by woshimeiguoren** [thelink2012/modloader#76]
Found file [0xFFFFFFFFFFFFFFFF] "INSANITY_AudioPack V2.1\Audio Pack\Install.txt" with handler "<none>"
No handler or callme for file "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\desktop.ini"
No handler or callme for file "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\desktop.ini"
Found file [0x00080008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_001.wav" with handler "gta3.std.bank"
Found file [0x00100008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_002.wav" with handler "gta3.std.bank"
Found file [0x00180008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_003.wav" with handler "gta3.std.bank"
Found file [0x00200008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_004.wav" with handler "gta3.std.bank"
Found file [0x00280008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_005.wav" with handler "gta3.std.bank"
Found file [0x00300008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_006.wav" with handler "gta3.std.bank"
Found file [0x00380008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_007.wav" with handler "gta3.std.bank"
Found file [0x00400008BECABFF9] "INSANITY_AudioPack V2.1\Audio Pack\modloader\INSANITY\INSANITY_Audio\FEET\Bank_001\sound_008.wav" with handler "gta3.std.bank"

**Comment by thelink2012** [comment]
What?

Em qua, 4 de jul de 2018 05:23, woshimeiguoren <notifications@github.com>
escreveu:
