### ISSUE TITLE
[Suggestion] - Add zipped files support + Mod description file.

### ISSUE THREAD

**Issue by RenanMsV** [thelink2012/modloader#82]
Add zipped files support + Mod description file.

Related #10.

So, after many years and with the tool pretty much done, what about you think about this suggestion again?

Add zipped files support (zip, rar, .7zip).

Recently a Vehicle Loader tool for Vice City was released. and with it the option to load mods from zipped files.
I feel it will be a good addition as it would reduce the modloader folder size.
https://www.mixmods.com.br/2019/03/vc-maxo-vehicle-loader-mvl.html

Also I suggest a modpack zipped file, which would contain many more zipped mods.
And a description file which would contain the mod description, such as author, description, and so.

The file stucture:

Mod_file.desc -- This file contains the mod descriptions, so it can be used to catalog mods in a website, or even a new in-game gui.

```ini
	Mod_author = Author
	Mod_desc = A mod that does something
	Mod_tags = tag1, tag2, tag3
	Mod_isSampReady = false
	Mod_blah = Another value here
```

Mod.zip - This is the mod zip file, this should contain the mod folder and the mod description file.

![mod.zip](https://i.imgur.com/HXdbJQX.jpg)

ModPack.zip - This is the modpack zip file, this should contain 1 or more mod zip files and the modpack description file.
![modpack.zip](https://i.imgur.com/fo9ZmSv.jpg)

**Comment by thelink2012** [comment]
Hi Renan,

This is a very interesting feature for many reasons, including the reduction in disk usage.

Unfortunately I do not have the time to continue supporting this tool. I'm quite glad I was able to leave it in a quite stable state to the community before dropping it, but I cannot afford to build it any further.

Appreciate the suggestion, and hope you understand.

**Comment by thelink2012** [comment]
Related #10
