### ISSUE TITLE
GTA VC 1.1 compatibility??

### ISSUE THREAD

**Issue by ghost** [thelink2012/modloader#92]
Without 1.1 compatibility, it is a pain in the ass installing mods that needs to replace some stuff in gta3.img. Especially with mods like Xbox Vehicles or Map Fixes where there is a lot of files to replace one by one via IMGTool. IMGTool is not very good since when you add a certain .dff or .txd, it doesn't replace the existing one so you have to dive in and find the file you want to replace just to overwrite it. The biggest problem is when you replace the 1.1 VC .exe to a 1.0 which causes the radio to get messed up. Best example of the radio getting messed up is by entering the Admiral or the Faggio in the beginning of the game. Both car and bike should play Billie Jean by Michael Jackson but plays a weird corrupted tune instead. Same happens for all radios. So I kinda need a workaround on getting Modloader to work on 1.1.

**Comment by thelink2012** [comment]
> The biggest problem is when you replace the 1.1 VC .exe to a 1.0 which causes the radio to get messed up. Best example of the radio getting messed up is by entering the Admiral or the Faggio in the beginning of the game. Both car and bike should play Billie Jean by Michael Jackson but plays a weird corrupted tune instead.

@ThirteenAG any idea on this? Are radio files different in 1.1?

@Back2Life888 I do not plan to support 1.1, a better solution here would be to develop a plugin to fix this issue. Better yet, you could replace the radio files with the ones from either 1.0 or Steam.

**Comment by ghost** [comment]
> > The biggest problem is when you replace the 1.1 VC .exe to a 1.0 which causes the radio to get messed up. Best example of the radio getting messed up is by entering the Admiral or the Faggio in the beginning of the game. Both car and bike should play Billie Jean by Michael Jackson but plays a weird corrupted tune instead.
> 
> @ThirteenAG any idea on this? Are radio files different in 1.1?
> 
> @Back2Life888 I do not plan to support 1.1, a better solution here would be to develop a plugin to fix this issue. Better yet, you could replace the radio files with the ones from either 1.0 or Steam.

just to let you know, it's quite hard finding the original 1.0 radio stations because you can't tell the difference on which is which. I don't wanna flood my whole C Drive with Vice City radio stations.

**Comment by mallardduck** [comment]
@thelink2012 - The steam version of the game shows as:
> GAT VC 1.1 UNK_REGION Steam

So I don't think using files from steam will help here. From what I see the scope of the project is being refined down to just GTA 3D era games. If that's the case, I wonder if you would support the versions that steam provides?

**Comment by thelink2012** [comment]
Hi @mallardduck

I suggest you to replace your Steam executable by an 1.0 one. The game files themselves are interchangeable between these executable versions. I can confirm because that's what I do.

You can find one at GameBurnWorld. If you are worried about malwares, mine has the md5sum [167a5c8b31b3e0dbefa033ca24453d4e](https://www.virustotal.com/gui/file/04e4db72629eaa786fdd182ac224f4fd6d68806f5f4fe5c1fb5f756dc4da11d7/detection).

**Comment by mallardduck** [comment]
Appreciate that - this seems to have worked just fine. Songs work fine too BTW.
